### ISSUE TITLE
Add new cosmetics and effects from TF2 summer update

### ISSUE THREAD

**Issue by BenKGIT** [offish/tf2-data#6]
The update from the 18th of July brought some new items, here is a list.
[https://www.reddit.com/r/tf2/comments/1e6lk4t/a_full_list_of_workshop_items_excluding_maps_that/](https://www.reddit.com/r/tf2/comments/1e6lk4t/a_full_list_of_workshop_items_excluding_maps_that/)

Do the skus need to be found manually or is there any tool/website which has all the ids?
If you don't plan to update this in the near future I would also be able to create a pull request soon.

**Comment by offish** [comment]
I'll update this later today.
